import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { createTerminalController, type TerminalSessionSnapshot } from './terminalController'

const snapshot = (changes: Partial<TerminalSessionSnapshot> = {}): TerminalSessionSnapshot => ({
  session_id: 'trial-1', request_id: 'request-1', cwd: '/project', shell: 'bash', cols: 80, rows: 24,
  status: 'running', exit_code: null, output: '$ ', first_sequence: 0, next_sequence: 2, truncated: false, ...changes,
})
function fixture() {
  let screen = ''
  const runtime = {
    open: vi.fn(async () => snapshot()), read: vi.fn(async () => snapshot()),
    write: vi.fn(async (_id: string, _data: string): Promise<void> => undefined),
    resize: vi.fn(async (_id: string, _cols: number, _rows: number) => undefined),
    stop: vi.fn(async () => snapshot({ status: 'stopped' })),
  }
  const renderer = { reset: vi.fn(() => screen = ''), write: vi.fn(async (output: string) => { screen += output }), screen: () => screen }
  const onSession = vi.fn(), onError = vi.fn(), onBusy = vi.fn()
  const controller = createTerminalController({ runtime, renderer, onSession, onError, onBusy })
  return { controller, runtime, renderer, onSession, onError, onBusy }
}
beforeEach(() => vi.useFakeTimers())
afterEach(() => vi.useRealTimers())

describe('terminal controller', () => {
  it('starts only explicitly, preserves ANSI, advances byte offsets, and records no input keys', async () => {
    const f = fixture()
    expect(f.runtime.open).not.toHaveBeenCalled()
    f.runtime.read.mockResolvedValueOnce(snapshot({ output: '\x1b[32m你好\x1b[0m\r\n$ ', next_sequence: 17 }))
    await f.controller.start(90, 30)
    expect(f.runtime.open).toHaveBeenCalledWith(90, 30)
    expect(f.runtime.read).toHaveBeenLastCalledWith('trial-1', null)
    await f.controller.write('secret-password\r')
    await f.controller.write('\x1b[A\x03')
    expect(f.runtime.write.mock.calls).toEqual([['trial-1', 'secret-password\r'], ['trial-1', '\x1b[A\x03']])
    expect(JSON.stringify(f.onSession.mock.lastCall)).not.toContain('secret-password')
    f.runtime.read.mockResolvedValueOnce(snapshot({ output: 'next', next_sequence: 21 }))
    await vi.advanceTimersByTimeAsync(200)
    expect(f.runtime.read).toHaveBeenLastCalledWith('trial-1', 17)
    expect(f.controller.session()?.output).toBe('\x1b[32m你好\x1b[0m\r\n$ next')
    expect(f.renderer.reset).toHaveBeenCalledTimes(1)
    f.controller.dispose()
  })
  it('resets the renderer when retained output skips bytes and preserves truncation', async () => {
    const f = fixture()
    await f.controller.start(80, 24)
    f.runtime.read.mockResolvedValueOnce(snapshot({ output: 'retained tail', first_sequence: 100, next_sequence: 113, truncated: true }))
    await vi.advanceTimersByTimeAsync(200)
    expect(f.renderer.reset).toHaveBeenCalledTimes(2)
    expect(f.controller.session()).toMatchObject({ output: 'retained tail', screen: 'retained tail', truncated: true })
    f.controller.dispose()
  })
  it('does not emit draft changes for idle polls', async () => {
    const f = fixture()
    await f.controller.start(80, 24)
    f.runtime.read.mockResolvedValue(snapshot({ output: '', next_sequence: 2 }))
    await vi.advanceTimersByTimeAsync(1000)
    expect(f.runtime.read).toHaveBeenCalledTimes(6)
    expect(f.onSession).toHaveBeenCalledTimes(2)
    f.controller.dispose()
  })
  it('answers terminal cursor queries during startup while ordinary input stays blocked', async () => {
    const f = fixture()
    f.renderer.write.mockImplementationOnce(async () => {
      await f.controller.write('blocked while connecting')
      await f.controller.write('\x1b[3;8R')
    })
    await f.controller.start(80, 24)
    expect(f.runtime.write.mock.calls).toEqual([['trial-1', '\x1b[3;8R']])
    f.controller.dispose()
  })
  it('stops polling at exit and unmount never stops the remote process', async () => {
    const f = fixture()
    await f.controller.start(80, 24)
    f.runtime.read.mockResolvedValueOnce(snapshot({ output: '\r\nbye', next_sequence: 7, status: 'exited', exit_code: 4 }))
    await vi.advanceTimersByTimeAsync(200)
    await vi.advanceTimersByTimeAsync(2000)
    expect(f.runtime.read).toHaveBeenCalledTimes(2)
    expect(f.controller.session()).toMatchObject({ status: 'exited', exit_code: 4 })
    f.controller.dispose()
    expect(f.runtime.stop).not.toHaveBeenCalled()
  })
  it('waits for queued input, stops the PTY, and persists the drained final output before submitting', async () => {
    const f = fixture()
    await f.controller.start(80, 24)
    let release!: () => void
    f.runtime.write.mockImplementationOnce(() => new Promise<void>((resolve) => release = resolve))
    const input = f.controller.write('command\r')
    await Promise.resolve()
    f.runtime.stop.mockResolvedValueOnce(snapshot({ output: '$ command\r\nfinal result', next_sequence: 23, status: 'stopped' }))
    const submitting = f.controller.prepareSubmission()
    await Promise.resolve()
    expect(f.runtime.stop).not.toHaveBeenCalled()
    release(); await input; await submitting
    expect(f.runtime.stop).toHaveBeenCalledWith('trial-1')
    expect(f.runtime.read).toHaveBeenCalledTimes(1)
    expect(f.controller.session()).toMatchObject({ status: 'stopped', output: '$ command\r\nfinal result', screen: '$ command\r\nfinal result' })
    await vi.advanceTimersByTimeAsync(2000)
    expect(f.runtime.read).toHaveBeenCalledTimes(1)
    f.controller.dispose()
  })
  it('blocks submission when stop fails and permits an explicit retry', async () => {
    const f = fixture()
    await f.controller.start(80, 24)
    const failure = new Error('Connection lost')
    f.runtime.stop.mockRejectedValueOnce(failure)
    await expect(f.controller.prepareSubmission()).rejects.toBe(failure)
    expect(f.onError).toHaveBeenCalledWith(failure)
    f.runtime.stop.mockResolvedValueOnce(snapshot({ status: 'stopped', output: '$ final', next_sequence: 7 }))
    await f.controller.prepareSubmission()
    expect(f.controller.session()?.status).toBe('stopped')
    f.controller.dispose()
  })
  it('disables input while locked but still drains output during submit', async () => {
    const f = fixture()
    await f.controller.start(80, 24)
    f.controller.setLocked(true)
    await f.controller.write('blocked')
    await f.controller.resize(100, 40)
    await f.controller.start(100, 40)
    expect(f.runtime.write).not.toHaveBeenCalled()
    expect(f.runtime.resize).not.toHaveBeenCalled()
    expect(f.runtime.open).toHaveBeenCalledTimes(1)
    f.runtime.stop.mockResolvedValueOnce(snapshot({ status: 'stopped', output: 'final', next_sequence: 5 }))
    await f.controller.prepareSubmission()
    expect(f.controller.session()?.screen).toBe('final')
    f.controller.dispose()
  })
  it('recovers a failed write after later input succeeds without replaying the failed input', async () => {
    const f = fixture()
    await f.controller.start(80, 24)
    const failure = new Error('Temporary write failure')
    f.runtime.write.mockRejectedValueOnce(failure)
    await expect(f.controller.write('uncertain')).rejects.toBe(failure)
    await expect(f.controller.prepareSubmission()).rejects.toBe(failure)
    await f.controller.write('new input')
    f.runtime.stop.mockResolvedValueOnce(snapshot({ status: 'stopped', output: 'final', next_sequence: 5 }))
    await f.controller.prepareSubmission()
    expect(f.runtime.write.mock.calls).toEqual([['trial-1', 'uncertain'], ['trial-1', 'new input']])
    expect(f.controller.session()?.status).toBe('stopped')
    f.controller.dispose()
  })
  it('bounds output on Unicode characters without splitting a surrogate pair', async () => {
    const f = fixture()
    f.runtime.read.mockResolvedValueOnce(snapshot({ output: 'a'.repeat(262_145) + '🙂', next_sequence: 262_149 }))
    await f.controller.start(80, 24)
    const state = f.controller.session()!
    expect([...state.output]).toHaveLength(262_144)
    expect(state.output.endsWith('🙂')).toBe(true)
    expect(state.truncated).toBe(true)
    expect([...state.screen]).toHaveLength(65_536)
    f.controller.dispose()
  })
  it('retires a permanently missing saved session and submits the preserved history without opening or stopping', async () => {
    const f = fixture()
    await f.controller.start(80, 24)
    const saved = f.controller.session()!
    const missing = { code: 'INVALID_ARGUMENT', message: 'The terminal session was not found for this request.', retryable: false }
    f.runtime.read.mockRejectedValueOnce(missing)
    await expect(f.controller.reconnect()).rejects.toBe(missing)
    expect(f.controller.session()).toEqual({ ...saved, status: 'stopped', exit_code: null })
    await f.controller.prepareSubmission()
    expect(f.runtime.open).toHaveBeenCalledTimes(1)
    expect(f.runtime.stop).not.toHaveBeenCalled()
    f.controller.dispose()
  })
  it('does not retire a saved session for transient transport failures', async () => {
    const f = fixture()
    await f.controller.start(80, 24)
    const failure = new Error('Network unavailable')
    f.runtime.read.mockRejectedValueOnce(failure)
    await expect(f.controller.reconnect()).rejects.toBe(failure)
    expect(f.controller.session()?.status).toBe('running')
    f.runtime.stop.mockRejectedValueOnce(failure)
    await expect(f.controller.prepareSubmission()).rejects.toBe(failure)
    expect(f.controller.session()?.status).toBe('running')
    f.controller.dispose()
  })
  it('drains an exited trial before explicit restart and renders the new session independently', async () => {
    const f = fixture()
    f.runtime.read.mockResolvedValueOnce(snapshot({ status: 'exited', output: 'first trial', exit_code: 0, next_sequence: 11 }))
    await f.controller.start(80, 24)
    f.runtime.stop.mockResolvedValueOnce(snapshot({ status: 'exited', output: 'first trial\r\nfinal tail', exit_code: 0, next_sequence: 23 }))
    f.runtime.open.mockResolvedValueOnce(snapshot({ session_id: 'trial-2' }))
    f.runtime.read.mockResolvedValueOnce(snapshot({ session_id: 'trial-2', output: 'second prompt', next_sequence: 13 }))
    await f.controller.start(80, 24)
    expect(f.runtime.stop.mock.invocationCallOrder[0]).toBeLessThan(f.runtime.open.mock.invocationCallOrder[1])
    expect(f.onSession.mock.calls.some(([session]) => session.id === 'trial-1' && session.output.endsWith('final tail'))).toBe(true)
    expect(f.runtime.read).toHaveBeenLastCalledWith('trial-2', null)
    expect(f.controller.session()).toMatchObject({ id: 'trial-2', output: 'second prompt', screen: 'second prompt' })
    f.controller.dispose()
  })
  it('preserves the stopped trial when a replacement cannot start', async () => {
    const f = fixture()
    await f.controller.start(80, 24)
    await f.controller.stop()
    const previous = f.controller.session()
    f.runtime.open.mockRejectedValueOnce(new Error('Shell unavailable'))
    await expect(f.controller.start(80, 24)).rejects.toThrow('Shell unavailable')
    expect(f.controller.session()).toEqual(previous)
    expect(f.runtime.stop).toHaveBeenCalledTimes(1)
    f.controller.dispose()
  })
  it('can explicitly restart a lost exited trial while preserving its known exit code', async () => {
    const f = fixture()
    f.runtime.read.mockResolvedValueOnce(snapshot({ status: 'exited', output: 'old history', exit_code: 9 }))
    await f.controller.start(80, 24)
    f.runtime.stop.mockRejectedValueOnce({ code: 'INVALID_ARGUMENT', message: 'The terminal session was not found for this request.' })
    f.runtime.open.mockResolvedValueOnce(snapshot({ session_id: 'trial-2' }))
    f.runtime.read.mockResolvedValueOnce(snapshot({ session_id: 'trial-2', output: 'new prompt' }))
    await f.controller.start(80, 24)
    expect(f.onSession.mock.calls.some(([session]) => session.id === 'trial-1' && session.exit_code === 9 && session.output === 'old history')).toBe(true)
    expect(f.controller.session()?.id).toBe('trial-2')
    f.controller.dispose()
  })
})
