export type SettingsSection =
  | 'general'
  | 'appearance'
  | 'permissions'
  | 'notifications'
  | 'voice'
  | 'post-processing'
  | 'shortcuts'
  | 'adapters'
  | 'agents'
  | 'web-access'
  | 'about'
