//! Custom notification sound files: import, commit, read, and remove.
//!
//! Uploaded audio is copied into `<library_root>/sounds/` with a UUID file
//! name. `commit` keeps only the committed file (replaced uploads never
//! accumulate); the frontend calls it only after the imported audio passed
//! duration validation.

use std::path::PathBuf;

use serde::Serialize;

use super::WorkbenchState;

const MAX_NOTIFICATION_SOUND_BYTES: u64 = 5 * 1024 * 1024;

const NOTIFICATION_SOUND_EXTENSIONS: [&str; 5] = ["mp3", "wav", "ogg", "m4a", "aac"];

#[derive(Debug, Serialize)]
pub(super) struct NotificationSoundImportView {
    id: String,
    name: String,
    bytes: Vec<u8>,
}

fn notification_sounds_dir(root: &std::path::Path) -> PathBuf {
    root.join("sounds")
}

fn valid_notification_sound_id(id: &str) -> bool {
    let Some((stem, extension)) = id.split_once('.') else {
        return false;
    };
    if !NOTIFICATION_SOUND_EXTENSIONS.contains(&extension) {
        return false;
    }
    // The stem is the UUID generated by import_notification_sound.
    if stem.len() != 36 {
        return false;
    }
    stem.bytes()
        .all(|byte| byte.is_ascii_hexdigit() || byte == b'-')
}

#[tauri::command]
pub(super) async fn import_notification_sound(
    path: PathBuf,
    state: tauri::State<'_, WorkbenchState>,
) -> Result<NotificationSoundImportView, String> {
    let file_name = path
        .file_name()
        .and_then(|value| value.to_str())
        .ok_or_else(|| "音频路径没有可读的文件名".to_owned())?
        .to_owned();
    let extension = path
        .extension()
        .and_then(|value| value.to_str())
        .map(|value| value.to_ascii_lowercase())
        .ok_or_else(|| "音频文件缺少扩展名".to_owned())?;
    if !NOTIFICATION_SOUND_EXTENSIONS.contains(&extension.as_str()) {
        return Err("仅支持 mp3、wav、ogg、m4a 格式的音频文件".to_owned());
    }
    let metadata = tokio::fs::metadata(&path)
        .await
        .map_err(|_| "无法读取所选音频文件".to_owned())?;
    if metadata.len() > MAX_NOTIFICATION_SOUND_BYTES {
        return Err("音频文件超过 5 MiB 限制".to_owned());
    }
    let contents = tokio::fs::read(&path)
        .await
        .map_err(|_| "无法读取所选音频文件".to_owned())?;
    let sounds_dir = notification_sounds_dir(&state.library_root());
    let id = format!("{}.{}", uuid::Uuid::new_v4(), extension);
    let target = sounds_dir.join(&id);
    let write_contents = contents.clone();
    tokio::task::spawn_blocking(move || -> Result<(), String> {
        std::fs::create_dir_all(&sounds_dir)
            .map_err(|error| format!("无法创建声音目录：{error}"))?;
        std::fs::write(&target, &write_contents)
            .map_err(|error| format!("无法保存音频文件：{error}"))?;
        Ok(())
    })
    .await
    .map_err(|error| format!("音频导入任务异常退出：{error}"))??;
    Ok(NotificationSoundImportView {
        id,
        name: file_name,
        bytes: contents,
    })
}

/// Keep only the committed file so replaced uploads never accumulate. The
/// frontend calls this only after the imported audio passed validation.
#[tauri::command]
pub(super) async fn commit_notification_sound(
    id: String,
    state: tauri::State<'_, WorkbenchState>,
) -> Result<(), String> {
    if !valid_notification_sound_id(&id) {
        return Err("无效的自定义提示音引用".to_owned());
    }
    let root = state.library_root();
    tokio::task::spawn_blocking(move || {
        let dir = notification_sounds_dir(&root);
        if let Ok(entries) = std::fs::read_dir(&dir) {
            for entry in entries.flatten() {
                if entry.file_name() != id.as_str() {
                    let _ = std::fs::remove_file(entry.path());
                }
            }
        }
    })
    .await
    .map_err(|error| format!("音频提交任务异常退出：{error}"))
}

#[tauri::command]
pub(super) async fn read_notification_sound(
    id: String,
    state: tauri::State<'_, WorkbenchState>,
) -> Result<Vec<u8>, String> {
    if !valid_notification_sound_id(&id) {
        return Err("无效的自定义提示音引用".to_owned());
    }
    let root = state.library_root();
    tokio::task::spawn_blocking(move || std::fs::read(notification_sounds_dir(&root).join(&id)))
        .await
        .map_err(|error| format!("音频读取任务异常退出：{error}"))?
        .map_err(|_| "自定义提示音文件不存在".to_owned())
}

#[tauri::command]
pub(super) async fn remove_notification_sound(
    id: String,
    state: tauri::State<'_, WorkbenchState>,
) -> Result<(), String> {
    if !valid_notification_sound_id(&id) {
        return Ok(());
    }
    let root = state.library_root();
    tokio::task::spawn_blocking(move || {
        let path = notification_sounds_dir(&root).join(&id);
        if path.exists() {
            let _ = std::fs::remove_file(path);
        }
    })
    .await
    .map_err(|error| format!("音频删除任务异常退出：{error}"))
}

#[cfg(test)]
mod tests {
    use super::valid_notification_sound_id;

    #[test]
    fn accepts_generated_notification_sound_ids() {
        let id = format!("{}.mp3", uuid::Uuid::new_v4());
        assert!(valid_notification_sound_id(&id));
    }

    #[test]
    fn rejects_unknown_extensions_and_paths() {
        assert!(!valid_notification_sound_id(""));
        assert!(!valid_notification_sound_id("custom.mp3"));
        assert!(!valid_notification_sound_id("..\\custom.mp3"));
        assert!(!valid_notification_sound_id("../../etc/passwd"));
        assert!(!valid_notification_sound_id(
            format!("{}.exe", uuid::Uuid::new_v4()).as_str()
        ));
        assert!(!valid_notification_sound_id(
            format!("{}.mp3", uuid::Uuid::new_v4())
                .replace('-', "/")
                .as_str()
        ));
    }
}
