use std::{fs, path::PathBuf};

use rambledesk_hosts::{ContinuationMode, HostAdapter, HostProfile};
use ts_rs::{Config, TS};

fn exported<T: TS>() -> String {
    T::decl(&Config::default()).replacen("type ", "export type ", 1)
}

fn main() -> std::io::Result<()> {
    let declarations = [
        exported::<HostAdapter>(),
        exported::<ContinuationMode>(),
        exported::<HostProfile>(),
    ];
    let output = format!(
        "/* This file is generated by `pnpm contracts:generate`. Do not edit. */\n\n{}\n",
        declarations.join("\n")
    );
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../apps/desktop/src/lib/generated/hosts.ts");
    fs::write(path, output)
}
