use std::{fs, path::PathBuf};

use rambledesk_core::{
    ActionInput, ContextRef, DraftView, ExecutionMode, FeedbackRequestSummary, FeedbackRequestView,
    FeedbackResultView, FeedbackStatus, FeedbackWorkspaceView, HealthSnapshot, SaveDraftInput,
    ServiceStatus, StorageStatus, SubmitFeedbackInput,
};
use ts_rs::{Config, TS};

fn exported<T: TS>() -> String {
    T::decl(&Config::default()).replacen("type ", "export type ", 1)
}

fn main() -> std::io::Result<()> {
    let declarations = [
        exported::<ServiceStatus>(),
        exported::<StorageStatus>(),
        exported::<HealthSnapshot>(),
    ];
    let output = format!(
        "/* This file is generated by `pnpm contracts:generate`. Do not edit. */\n\n{}\n",
        declarations.join("\n")
    );

    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../apps/desktop/src/lib/generated/health.ts");
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, output)?;

    let declarations = [
        exported::<FeedbackStatus>(),
        exported::<ExecutionMode>(),
        exported::<ActionInput>(),
        exported::<ContextRef>(),
        exported::<FeedbackResultView>(),
        exported::<FeedbackRequestView>(),
        exported::<FeedbackRequestSummary>(),
        exported::<DraftView>(),
        exported::<FeedbackWorkspaceView>(),
        exported::<SaveDraftInput>(),
        exported::<SubmitFeedbackInput>(),
    ];
    let output = format!(
        "/* This file is generated by `pnpm contracts:generate`. Do not edit. */\n\n{}\n",
        declarations.join("\n")
    );
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../apps/desktop/src/lib/generated/feedback.ts");
    fs::write(path, output)
}
