use std::{fs, path::PathBuf};

use rambledesk_core::{
    ActionInput, AddAttachmentInput, ApproveFeedbackInput, AttachmentView, CancelFeedbackInput,
    ContextRef, DeleteFeedbackRequestInput, DraftView, ExecutionMode, FeedbackRequestSummary,
    FeedbackRequestView, FeedbackResolution, FeedbackResultView, FeedbackStatus,
    FeedbackWorkspaceView, HostSessionInput, HostSessionSummary, ListFeedbackRequestsInput,
    ListFeedbackRequestsOutput, ListHostSessionsInput, RecoverFeedbackInput, RemoveAttachmentInput,
    RenameHostSessionInput, ReorderAttachmentsInput, RequestAttachmentView, SaveDraftInput,
    SetHostPinnedInput, SetHostSessionPinnedInput, SubmitFeedbackInput,
};
use ts_rs::{Config, TS};

fn exported<T: TS>() -> String {
    T::decl(&Config::default()).replacen("type ", "export type ", 1)
}

fn main() -> std::io::Result<()> {
    let declarations = [
        exported::<FeedbackStatus>(),
        exported::<FeedbackResolution>(),
        exported::<ExecutionMode>(),
        exported::<ActionInput>(),
        exported::<ContextRef>(),
        exported::<FeedbackResultView>(),
        exported::<FeedbackRequestView>(),
        exported::<FeedbackRequestSummary>(),
        exported::<HostSessionSummary>(),
        exported::<HostSessionInput>(),
        exported::<RenameHostSessionInput>(),
        exported::<SetHostSessionPinnedInput>(),
        exported::<SetHostPinnedInput>(),
        exported::<ListHostSessionsInput>(),
        exported::<ListFeedbackRequestsInput>(),
        exported::<ListFeedbackRequestsOutput>(),
        exported::<DeleteFeedbackRequestInput>(),
        exported::<DraftView>(),
        exported::<AttachmentView>(),
        exported::<RequestAttachmentView>(),
        exported::<FeedbackWorkspaceView>(),
        exported::<AddAttachmentInput>(),
        exported::<RemoveAttachmentInput>(),
        exported::<ReorderAttachmentsInput>(),
        exported::<SaveDraftInput>(),
        exported::<SubmitFeedbackInput>(),
        exported::<CancelFeedbackInput>(),
        exported::<ApproveFeedbackInput>(),
        exported::<RecoverFeedbackInput>(),
    ];
    let output = format!(
        "/* This file is generated by `pnpm contracts:generate`. Do not edit. */\n\n{}\n",
        declarations.join("\n")
    );
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../apps/desktop/src/lib/generated/feedback.ts");
    fs::write(path, output)
}
